# files/settings.yml
general:
  artefacts_dir: /Users/saketm10/Projects/color_matching/scratch

swatch_matcher:
  args:
    swatch_path: /Users/saketm10/Projects/color_matching/dataset/hair_swatches
    device: mps
    hair_segmentation_candidate: MediapipeHairSegmenter
    embedding_candidate: ViTB32Infer
    models:
      - MediapipeHairSegmenter
      - ViTB32Infer

swatch_match_generator:
  args:
    swatch_path: /Users/saketm10/Projects/color_matching/dataset/hair_swatches
    device: mps
    vlm_candidate: QwenV25Infer
    models:
      - QwenV25Infer

hair_match_generator:
  args:
    swatch_path: /Users/saketm10/Projects/color_matching/dataset/hair_swatches

model_manager:
  general:
    huggingface_api_token: ""
    model_loading: "local"
    cache_dir: "models/cache"
  models:
    QwenV25Infer:
      model_name_or_url: "Qwen/Qwen2.5-VL-3B-Instruct"
      device: mps
      api_endpoint": ""
    ColPaliInfer:
      model_name_or_url: "vidore/colqwen2-v1.0"
      device: mps
      api_endpoint": ""
    ViTB32Infer:
      model_name_or_url: "openai/clip-vit-base-patch32"
      device: mps
      api_endpoint": ""
    MediapipeHairSegmenter:
      model_name_or_url: "mediapipe_model"
      device: mps
      api_endpoint": ""

shared:
  artifacts_dir: others

swatch_details:
  args:
    save_path: dataset/swatch_details.json

